//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 07:55:14 PM IST 
//


package com.fedex.validation.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for multipleShipmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="multipleShipmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PKGSEQUENCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PKGSEQUENCE_ORIGINAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FORMCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRKNGNBR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SHPWGT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DECVALAMT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CARRVALAMT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIM1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SP_SHPWGT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RELSIGTYP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="REFINFODESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="REFINFODESC2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="REFINFODESC3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RMA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PONBR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DRYICEFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HAZMATFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NSPFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PAFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ORMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LITHBA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PAPLUSFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DRYICEUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DRYICEWGT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DANGGOODSFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODDVFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ALCFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADDCODCHRGFLG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODAMT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CUSTREF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODRTRNREF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MW_GRP_NBR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NONTRANSID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UNID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WARMSREFID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ALCRECPTYP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ALCLBLTYP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RSCBNDLID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HARMCD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CMDYWGT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UNITVALAMT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CMDYCSTMAMT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="COMMODITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SQE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FLATRATEBOX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PAAIND" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SAVECERTI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multipleShipmentType", propOrder = {
    "pkgsequence",
    "pkgsequenceoriginal",
    "formcd",
    "trkngnbr",
    "shpwgt",
    "decvalamt",
    "carrvalamt",
    "dim",
    "dim1",
    "spshpwgt",
    "relsigtyp",
    "refinfodesc",
    "refinfodesc2",
    "refinfodesc3",
    "rma",
    "ponbr",
    "dryiceflg",
    "hazmatflg",
    "nspflg",
    "paflg",
    "ormd",
    "lithba",
    "paplusflg",
    "dryiceum",
    "dryicewgt",
    "danggoodsflg",
    "coddvflg",
    "alcflg",
    "addcodchrgflg",
    "codamt",
    "custref",
    "codrtrnref",
    "mwgrpnbr",
    "nontransid",
    "unid",
    "warmsrefid",
    "alcrecptyp",
    "alclbltyp",
    "rscbndlid",
    "harmcd",
    "cmdywgt",
    "unitvalamt",
    "cmdycstmamt",
    "commodity",
    "sqe",
    "flatratebox",
    "paaind",
    "savecerti"
})
public class MultipleShipmentType {

    @XmlElement(name = "PKGSEQUENCE", required = true)
    protected String pkgsequence;
    @XmlElement(name = "PKGSEQUENCE_ORIGINAL", required = true)
    protected String pkgsequenceoriginal;
    @XmlElement(name = "FORMCD", required = true)
    protected String formcd;
    @XmlElement(name = "TRKNGNBR", required = true)
    protected String trkngnbr;
    @XmlElement(name = "SHPWGT", required = true)
    protected String shpwgt;
    @XmlElement(name = "DECVALAMT", required = true)
    protected String decvalamt;
    @XmlElement(name = "CARRVALAMT", required = true)
    protected String carrvalamt;
    @XmlElement(name = "DIM", required = true)
    protected String dim;
    @XmlElement(name = "DIM1", required = true)
    protected String dim1;
    @XmlElement(name = "SP_SHPWGT", required = true)
    protected String spshpwgt;
    @XmlElement(name = "RELSIGTYP", required = true)
    protected String relsigtyp;
    @XmlElement(name = "REFINFODESC", required = true)
    protected String refinfodesc;
    @XmlElement(name = "REFINFODESC2", required = true)
    protected String refinfodesc2;
    @XmlElement(name = "REFINFODESC3", required = true)
    protected String refinfodesc3;
    @XmlElement(name = "RMA", required = true)
    protected String rma;
    @XmlElement(name = "PONBR", required = true)
    protected String ponbr;
    @XmlElement(name = "DRYICEFLG", required = true)
    protected String dryiceflg;
    @XmlElement(name = "HAZMATFLG", required = true)
    protected String hazmatflg;
    @XmlElement(name = "NSPFLG", required = true)
    protected String nspflg;
    @XmlElement(name = "PAFLG", required = true)
    protected String paflg;
    @XmlElement(name = "ORMD", required = true)
    protected String ormd;
    @XmlElement(name = "LITHBA", required = true)
    protected String lithba;
    @XmlElement(name = "PAPLUSFLG", required = true)
    protected String paplusflg;
    @XmlElement(name = "DRYICEUM", required = true)
    protected String dryiceum;
    @XmlElement(name = "DRYICEWGT", required = true)
    protected String dryicewgt;
    @XmlElement(name = "DANGGOODSFLG", required = true)
    protected String danggoodsflg;
    @XmlElement(name = "CODDVFLG", required = true)
    protected String coddvflg;
    @XmlElement(name = "ALCFLG", required = true)
    protected String alcflg;
    @XmlElement(name = "ADDCODCHRGFLG", required = true)
    protected String addcodchrgflg;
    @XmlElement(name = "CODAMT", required = true)
    protected String codamt;
    @XmlElement(name = "CUSTREF", required = true)
    protected String custref;
    @XmlElement(name = "CODRTRNREF", required = true)
    protected String codrtrnref;
    @XmlElement(name = "MW_GRP_NBR", required = true)
    protected String mwgrpnbr;
    @XmlElement(name = "NONTRANSID", required = true)
    protected String nontransid;
    @XmlElement(name = "UNID", required = true)
    protected String unid;
    @XmlElement(name = "WARMSREFID", required = true)
    protected String warmsrefid;
    @XmlElement(name = "ALCRECPTYP", required = true)
    protected String alcrecptyp;
    @XmlElement(name = "ALCLBLTYP", required = true)
    protected String alclbltyp;
    @XmlElement(name = "RSCBNDLID", required = true)
    protected String rscbndlid;
    @XmlElement(name = "HARMCD", required = true)
    protected String harmcd;
    @XmlElement(name = "CMDYWGT", required = true)
    protected String cmdywgt;
    @XmlElement(name = "UNITVALAMT", required = true)
    protected String unitvalamt;
    @XmlElement(name = "CMDYCSTMAMT", required = true)
    protected String cmdycstmamt;
    @XmlElement(name = "COMMODITY", required = true)
    protected String commodity;
    @XmlElement(name = "SQE", required = true)
    protected String sqe;
    @XmlElement(name = "FLATRATEBOX", required = true)
    protected String flatratebox;
    @XmlElement(name = "PAAIND", required = true)
    protected String paaind;
    @XmlElement(name = "SAVECERTI", required = true)
    protected String savecerti;

    /**
     * Gets the value of the pkgsequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPKGSEQUENCE() {
        return pkgsequence;
    }

    /**
     * Sets the value of the pkgsequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPKGSEQUENCE(String value) {
        this.pkgsequence = value;
    }

    /**
     * Gets the value of the pkgsequenceoriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPKGSEQUENCEORIGINAL() {
        return pkgsequenceoriginal;
    }

    /**
     * Sets the value of the pkgsequenceoriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPKGSEQUENCEORIGINAL(String value) {
        this.pkgsequenceoriginal = value;
    }

    /**
     * Gets the value of the formcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORMCD() {
        return formcd;
    }

    /**
     * Sets the value of the formcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORMCD(String value) {
        this.formcd = value;
    }

    /**
     * Gets the value of the trkngnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRKNGNBR() {
        return trkngnbr;
    }

    /**
     * Sets the value of the trkngnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRKNGNBR(String value) {
        this.trkngnbr = value;
    }

    /**
     * Gets the value of the shpwgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHPWGT() {
        return shpwgt;
    }

    /**
     * Sets the value of the shpwgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHPWGT(String value) {
        this.shpwgt = value;
    }

    /**
     * Gets the value of the decvalamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDECVALAMT() {
        return decvalamt;
    }

    /**
     * Sets the value of the decvalamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDECVALAMT(String value) {
        this.decvalamt = value;
    }

    /**
     * Gets the value of the carrvalamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCARRVALAMT() {
        return carrvalamt;
    }

    /**
     * Sets the value of the carrvalamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCARRVALAMT(String value) {
        this.carrvalamt = value;
    }

    /**
     * Gets the value of the dim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIM() {
        return dim;
    }

    /**
     * Sets the value of the dim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIM(String value) {
        this.dim = value;
    }

    /**
     * Gets the value of the dim1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIM1() {
        return dim1;
    }

    /**
     * Sets the value of the dim1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIM1(String value) {
        this.dim1 = value;
    }

    /**
     * Gets the value of the spshpwgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPSHPWGT() {
        return spshpwgt;
    }

    /**
     * Sets the value of the spshpwgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPSHPWGT(String value) {
        this.spshpwgt = value;
    }

    /**
     * Gets the value of the relsigtyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRELSIGTYP() {
        return relsigtyp;
    }

    /**
     * Sets the value of the relsigtyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRELSIGTYP(String value) {
        this.relsigtyp = value;
    }

    /**
     * Gets the value of the refinfodesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFINFODESC() {
        return refinfodesc;
    }

    /**
     * Sets the value of the refinfodesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFINFODESC(String value) {
        this.refinfodesc = value;
    }

    /**
     * Gets the value of the refinfodesc2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFINFODESC2() {
        return refinfodesc2;
    }

    /**
     * Sets the value of the refinfodesc2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFINFODESC2(String value) {
        this.refinfodesc2 = value;
    }

    /**
     * Gets the value of the refinfodesc3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFINFODESC3() {
        return refinfodesc3;
    }

    /**
     * Sets the value of the refinfodesc3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFINFODESC3(String value) {
        this.refinfodesc3 = value;
    }

    /**
     * Gets the value of the rma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRMA() {
        return rma;
    }

    /**
     * Sets the value of the rma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRMA(String value) {
        this.rma = value;
    }

    /**
     * Gets the value of the ponbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPONBR() {
        return ponbr;
    }

    /**
     * Sets the value of the ponbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPONBR(String value) {
        this.ponbr = value;
    }

    /**
     * Gets the value of the dryiceflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRYICEFLG() {
        return dryiceflg;
    }

    /**
     * Sets the value of the dryiceflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRYICEFLG(String value) {
        this.dryiceflg = value;
    }

    /**
     * Gets the value of the hazmatflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHAZMATFLG() {
        return hazmatflg;
    }

    /**
     * Sets the value of the hazmatflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHAZMATFLG(String value) {
        this.hazmatflg = value;
    }

    /**
     * Gets the value of the nspflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNSPFLG() {
        return nspflg;
    }

    /**
     * Sets the value of the nspflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNSPFLG(String value) {
        this.nspflg = value;
    }

    /**
     * Gets the value of the paflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAFLG() {
        return paflg;
    }

    /**
     * Sets the value of the paflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAFLG(String value) {
        this.paflg = value;
    }

    /**
     * Gets the value of the ormd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORMD() {
        return ormd;
    }

    /**
     * Sets the value of the ormd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORMD(String value) {
        this.ormd = value;
    }

    /**
     * Gets the value of the lithba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLITHBA() {
        return lithba;
    }

    /**
     * Sets the value of the lithba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLITHBA(String value) {
        this.lithba = value;
    }

    /**
     * Gets the value of the paplusflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAPLUSFLG() {
        return paplusflg;
    }

    /**
     * Sets the value of the paplusflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAPLUSFLG(String value) {
        this.paplusflg = value;
    }

    /**
     * Gets the value of the dryiceum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRYICEUM() {
        return dryiceum;
    }

    /**
     * Sets the value of the dryiceum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRYICEUM(String value) {
        this.dryiceum = value;
    }

    /**
     * Gets the value of the dryicewgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRYICEWGT() {
        return dryicewgt;
    }

    /**
     * Sets the value of the dryicewgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRYICEWGT(String value) {
        this.dryicewgt = value;
    }

    /**
     * Gets the value of the danggoodsflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDANGGOODSFLG() {
        return danggoodsflg;
    }

    /**
     * Sets the value of the danggoodsflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDANGGOODSFLG(String value) {
        this.danggoodsflg = value;
    }

    /**
     * Gets the value of the coddvflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODDVFLG() {
        return coddvflg;
    }

    /**
     * Sets the value of the coddvflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODDVFLG(String value) {
        this.coddvflg = value;
    }

    /**
     * Gets the value of the alcflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALCFLG() {
        return alcflg;
    }

    /**
     * Sets the value of the alcflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALCFLG(String value) {
        this.alcflg = value;
    }

    /**
     * Gets the value of the addcodchrgflg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDCODCHRGFLG() {
        return addcodchrgflg;
    }

    /**
     * Sets the value of the addcodchrgflg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDCODCHRGFLG(String value) {
        this.addcodchrgflg = value;
    }

    /**
     * Gets the value of the codamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODAMT() {
        return codamt;
    }

    /**
     * Sets the value of the codamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODAMT(String value) {
        this.codamt = value;
    }

    /**
     * Gets the value of the custref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTREF() {
        return custref;
    }

    /**
     * Sets the value of the custref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTREF(String value) {
        this.custref = value;
    }

    /**
     * Gets the value of the codrtrnref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODRTRNREF() {
        return codrtrnref;
    }

    /**
     * Sets the value of the codrtrnref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODRTRNREF(String value) {
        this.codrtrnref = value;
    }

    /**
     * Gets the value of the mwgrpnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMWGRPNBR() {
        return mwgrpnbr;
    }

    /**
     * Sets the value of the mwgrpnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMWGRPNBR(String value) {
        this.mwgrpnbr = value;
    }

    /**
     * Gets the value of the nontransid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNONTRANSID() {
        return nontransid;
    }

    /**
     * Sets the value of the nontransid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNONTRANSID(String value) {
        this.nontransid = value;
    }

    /**
     * Gets the value of the unid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNID() {
        return unid;
    }

    /**
     * Sets the value of the unid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNID(String value) {
        this.unid = value;
    }

    /**
     * Gets the value of the warmsrefid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWARMSREFID() {
        return warmsrefid;
    }

    /**
     * Sets the value of the warmsrefid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWARMSREFID(String value) {
        this.warmsrefid = value;
    }

    /**
     * Gets the value of the alcrecptyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALCRECPTYP() {
        return alcrecptyp;
    }

    /**
     * Sets the value of the alcrecptyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALCRECPTYP(String value) {
        this.alcrecptyp = value;
    }

    /**
     * Gets the value of the alclbltyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALCLBLTYP() {
        return alclbltyp;
    }

    /**
     * Sets the value of the alclbltyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALCLBLTYP(String value) {
        this.alclbltyp = value;
    }

    /**
     * Gets the value of the rscbndlid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRSCBNDLID() {
        return rscbndlid;
    }

    /**
     * Sets the value of the rscbndlid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRSCBNDLID(String value) {
        this.rscbndlid = value;
    }

    /**
     * Gets the value of the harmcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHARMCD() {
        return harmcd;
    }

    /**
     * Sets the value of the harmcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHARMCD(String value) {
        this.harmcd = value;
    }

    /**
     * Gets the value of the cmdywgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMDYWGT() {
        return cmdywgt;
    }

    /**
     * Sets the value of the cmdywgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMDYWGT(String value) {
        this.cmdywgt = value;
    }

    /**
     * Gets the value of the unitvalamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITVALAMT() {
        return unitvalamt;
    }

    /**
     * Sets the value of the unitvalamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITVALAMT(String value) {
        this.unitvalamt = value;
    }

    /**
     * Gets the value of the cmdycstmamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMDYCSTMAMT() {
        return cmdycstmamt;
    }

    /**
     * Sets the value of the cmdycstmamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMDYCSTMAMT(String value) {
        this.cmdycstmamt = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMODITY() {
        return commodity;
    }

    /**
     * Sets the value of the commodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMODITY(String value) {
        this.commodity = value;
    }

    /**
     * Gets the value of the sqe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSQE() {
        return sqe;
    }

    /**
     * Sets the value of the sqe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSQE(String value) {
        this.sqe = value;
    }

    /**
     * Gets the value of the flatratebox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLATRATEBOX() {
        return flatratebox;
    }

    /**
     * Sets the value of the flatratebox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLATRATEBOX(String value) {
        this.flatratebox = value;
    }

    /**
     * Gets the value of the paaind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAAIND() {
        return paaind;
    }

    /**
     * Sets the value of the paaind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAAIND(String value) {
        this.paaind = value;
    }

    /**
     * Gets the value of the savecerti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAVECERTI() {
        return savecerti;
    }

    /**
     * Sets the value of the savecerti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAVECERTI(String value) {
        this.savecerti = value;
    }

}
