//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 07:55:14 PM IST 
//


package com.fedex.validation.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shippingInformation2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shippingInformation2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MPSSHPWGT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SHPTOTALWGT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MPS_TOTCUSTVAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MPS_DECVAL_AMT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shippingInformation2Type", propOrder = {
    "mpsshpwgt",
    "shptotalwgt",
    "mpstotcustval",
    "mpsdecvalamt"
})
public class ShippingInformation2Type {

    @XmlElement(name = "MPSSHPWGT", required = true)
    protected String mpsshpwgt;
    @XmlElement(name = "SHPTOTALWGT", required = true)
    protected String shptotalwgt;
    @XmlElement(name = "MPS_TOTCUSTVAL", required = true)
    protected String mpstotcustval;
    @XmlElement(name = "MPS_DECVAL_AMT", required = true)
    protected String mpsdecvalamt;

    /**
     * Gets the value of the mpsshpwgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMPSSHPWGT() {
        return mpsshpwgt;
    }

    /**
     * Sets the value of the mpsshpwgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMPSSHPWGT(String value) {
        this.mpsshpwgt = value;
    }

    /**
     * Gets the value of the shptotalwgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHPTOTALWGT() {
        return shptotalwgt;
    }

    /**
     * Sets the value of the shptotalwgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHPTOTALWGT(String value) {
        this.shptotalwgt = value;
    }

    /**
     * Gets the value of the mpstotcustval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMPSTOTCUSTVAL() {
        return mpstotcustval;
    }

    /**
     * Sets the value of the mpstotcustval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMPSTOTCUSTVAL(String value) {
        this.mpstotcustval = value;
    }

    /**
     * Gets the value of the mpsdecvalamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMPSDECVALAMT() {
        return mpsdecvalamt;
    }

    /**
     * Sets the value of the mpsdecvalamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMPSDECVALAMT(String value) {
        this.mpsdecvalamt = value;
    }

}
